### ISSUE TITLE
Does not decode headers according to RFC2047

### ISSUE THREAD

**Issue by eXorus** [eXorus/php-mime-mail-parser#3]
What steps will reproduce the problem?
* Parse a message with a header (i.e. subject line) encoded according to
RFC2047

What is the expected output? What do you see instead?
* Expected output is the decoded subject line
* Instead, the subject line is passed through unencoded, i.e.
=?UTF-8?Q?stuff_A=C3=A5_B=E2=88=AB_C=C3=A7_D=E2=88=82_E?=
=?UTF-8?Q?=C2=B4_R=C2=AE_$=C2=A2?=

What version of the product are you using? On what operating system?
* Revision 15

Please provide any additional information below.
* Attached is a diff of my changes to properly decode the message headers
if they are encoded. The code is mostly copied from Pear's Mail_Mime class.
* This also fixes the issue where the message body is not decoded properly
based on its encoding type

Source : https://code.google.com/p/php-mime-mail-parser/issues/detail?id=8

**Comment by vadito** [comment]
Issue seems to be back in a slightly different format. The current imap_utf8 solution in the code is not working if only a part of the header line is encoded. I encountered the problem with `Subject: [ASCII-STRING] =?utf-8?Q?bej=C3=B6v=C5=91` style subjects. 
I don't know if this is a bug in the sending client or the library, but `imap_mime_header_decode` decodes the line corretly.

**Comment by eXorus** [comment]
i know I can improve this function decodeHeader($input)

I would like to parse it with regex  =? [charset] ? [EncodingTransfert] ? [name]
and used decodeContentTransfer() and decodeCharset()

I don't have the time for the moment but I have this idea to implement and I hope it will fix all the issues. If you have time to help me, welcome.

**Comment by clementhk** [comment]
Something like this, @eXorus? https://code.google.com/p/php-mime-mail-parser/issues/attachmentText?id=8&aid=8474390881923146156&name=diff.txt&token=ABZ6GAc0y2KVajmd4tmaSzTKFJyLPa2_SQ%3A1423129620122

I don't really get the problem though, "only a part of the header line is encoded"? Is there a sample of it?

**Comment by vadito** [comment]
@clementhk 
Some test messages came in with a subject like this:
`[PRJ-OTH] asdf  =?utf-8?Q?=C3=A1rv=C3=ADzt=C5=B1r=C5=91_t=C3=BCk=C3=B6rf=C3=BAr=C3=B3g=C3=A9p?=`
imap_utf8 isn't doing anything with it
```
echo imap_utf8($subj); =>
'[PRJ-OTH] asdf  =?utf-8?Q?=C3=A1rv=C3=ADzt=C5=B1r=C5=91_t=C3=BCk=C3=B6rf=C3=BAr=C3=B3g=C3=A9p?='
```
`imap_mime_header_decode` decodes the parts correctly
```
array(
	(int) 0 => object(stdClass) {
		charset => 'default'
		text => '[PRJ-OTH] asdf '
	},
	(int) 1 => object(stdClass) {
		charset => 'utf-8'
		text => 'árvíztűrő tükörfúrógép'
	}
)
```
I'm not sure if that's a library issue or a client problem, the lib decodes some subjects correctly, some fail.
