### ISSUE TITLE
attachment size

### ISSUE THREAD

**Issue by thierryve** [eXorus/php-mime-mail-parser#36]
Hi,

First of all you made a great library.
In the attachment class I would like a method that returns the size of an attachment.

Let me know what you think.

**Comment by eXorus** [comment]
Hello,

Yes it's possible. Do you have already the function ?

**Comment by thierryve** [comment]
Not yet. I hope I have some time tomorrow

**Comment by thierryve** [comment]
I didn't test it but I think this does the trick
```PHP
    /**
     * Calculate the size of the attachment
     * @return int
     */
    public function getSize()
    {
        return mb_strlen($this->getContent());
    }
```

**Comment by clementhk** [comment]
@thierryve i don't think this lib has dependency of `mb_`.

**Comment by eXorus** [comment]
I didn't had a function because you can used filesize from PHP.

I updated Readme with an example.
